Feature/checksums
stackhpc/ansible-role-os-images pull request #11
Opened 2018-07-06 16:46 UTC by jovial

This will only re-upload an image if the checksums differ. You can also choose whether two delete the old image or rename it. The renamed images look like:

```
(os2) [hpcszum2@eod-control images]$ openstack image list
+--------------------------------------+---------------------------------+--------+
| ID                                   | Name                            | Status |
+--------------------------------------+---------------------------------+--------+
| c547a675-8966-4589-b9d4-e27fc2b8ffa5 | CentOS7.5                       | active |
| fc2541e6-f998-42cf-931b-42fe3a5fce42 | CentOS7.5-IB                    | active |
| c3948899-007a-4e65-bddf-e91bb1fb6bf3 | CentOS7.5-OpenHPC               | active |
| 2a116460-13f1-47b7-b5c6-2b0f24e2c396 | delete_me2                      | active |
| 76971079-d2b2-46fe-8be7-18c443958550 | ipa.initramfs                   | active |
| 66f7b5ad-4fc4-4b9a-ae63-daf458ff1f85 | ipa.vmlinuz                     | active |
| b30960d1-a55b-4aeb-be68-2da7d0ea5956 | wjs                             | active |
| 3f83dea2-4468-4a17-bac7-5b7d62225eb6 | wjs-2018-07-06-16-41-29         | active |
| 2c341119-a278-4ee4-8aea-830d03b560d0 | wjs-kernel                      | active |
| b6e9feb3-3f74-4e34-a067-c680f808fb6a | wjs-ramdisk                     | active |
| 726acf96-b17d-4779-b2f8-2d6c4565d3ca | wjs-ramdisk-2018-07-06-16-41-28 | active |
+--------------------------------------+---------------------------------+--------+
```
In the example I was building the wjs image (notice the kernel didn't change).

2018-08-23 11:03 UTC, markgoddard requested changes
Sorry for the review delay.

It's probably time to split the tasks file into build.yml and upload.yml, but let's not do that in this PR to keep the diff clean.

2018-08-23 11:03 UTC, markgoddard commented on defaults/main.yml
> +  OS_AUTH_URL: "{{ os_images_auth.auth_url }}"
Might need to add OS_USER_DOMAIN_NAME, OS_PROJECT_DOMAIN_NAME and OS_INTERFACE here (with default in case they aren't set)

2018-08-23 11:03 UTC, markgoddard commented on tasks/main.yml
> +      with_items: "{{ results | json_query(query) }}"
As I recently found out, this adds a dependency on jmespath, we should note that in the README.

2018-08-23 11:03 UTC, markgoddard commented on tasks/main.yml
> +        - glance_metadata[image_key]["checksum"] != local_checksums[item.name ~ '.vmlinuz']
Not  sure about the logic here. Shouldn't it be:

policy == overwrite AND (force rebuild OR checksums differ)

2018-08-23 11:03 UTC, markgoddard commented on tasks/main.yml
>          name: "{{ item.name ~ '-kernel' }}"
image_key?

2018-08-23 11:03 UTC, markgoddard commented on tasks/main.yml
> +        - glance_metadata[image_key]["checksum"] != local_checksums[item.name ~ ".vmlinuz"]
Similar to above:

policy == rename AND (force rebuild OR checksums differ)

2018-08-23 11:03 UTC, markgoddard commented on README.md
> +
Needs openstack_auth_env

2018-08-23 11:03 UTC, markgoddard commented on tasks/main.yml
> +
errant newline?

2018-08-23 11:03 UTC, markgoddard commented on tasks/main.yml
>          name: "{{ item.name }}"
image_key?

2018-11-06 10:06 UTC, brtknr submitted a review, later dismissed

2018-11-06 10:40 UTC, jovial commented on defaults/main.yml
> +  OS_AUTH_URL: "{{ os_images_auth.auth_url }}"
I've made `os_auth_images` get the defaults from `os_images_env`as the info contained in `os_images_env` seems to be a superset of `os_images_auth`

2018-11-06 10:48 UTC, markgoddard commented on defaults/main.yml
> +  OS_AUTH_URL: "{{ os_images_auth.auth_url }}"
Isn't there a reference loop there?

2018-11-06 11:28 UTC, jovial commented on tasks/main.yml
> +        - glance_metadata[image_key]["checksum"] != local_checksums[item.name ~ '.vmlinuz']
Do we still want to upload even if the checksums match?

2018-11-06 12:02 UTC, markgoddard commented on tasks/main.yml
> +        - glance_metadata[image_key]["checksum"] != local_checksums[item.name ~ '.vmlinuz']
I guess not. Maybe we can just remove force rebuild from the conditions?

2018-11-06 13:02 UTC, brtknr commented
Do we need both os_images_auth_env and os_images_auth? Cant we just rename os_images_auth_env to os_images_auth and leave it there?

2018-11-06 13:06 UTC, jovial commented
> There is a slight backwards compatibility issue with this approach. Previously, the way you configured auth was by setting os_images_auth, using whatever method you like. Now you'd have to also set environment variables. It's probably not a problem since we tend to use environment variables in tools that use this role.

Damn, good point - I remember why I did it the other way now. Can we construct it in such a way to maintain backwards compatibility?

> Do we need both os_images_auth_env and os_images_auth? Cant we just rename os_images_auth_env to os_images_auth and leave it there?

The keys in the dictionary are named slightly differently (case mainly)

2019-05-23 15:42 UTC, brtknr commented
This branch has a merge conflict now @jovial :( 

Is the title "Force rebuild image and reupload" accurate given that this is already possible using the `os_images_force_rebuild=true` flag?

2023-11-23 10:01 UTC, oneswig commented
Closing this, I think the functionality has been independently created

2023-11-23 10:01 UTC, closed without merging