Add support for region
stackhpc/ansible-role-os-images pull request #44
Opened 2021-05-20 09:29 UTC by brtknr

2021-05-20 10:20 UTC, markgoddard requested changes

2021-05-20 10:20 UTC, markgoddard commented on tasks/main.yml
>          interface: "{{ os_images_interface | default(omit, true) }}"
nit: connection/auth parameters are grouped first

2021-05-20 10:23 UTC, brtknr commented on tasks/main.yml
>          interface: "{{ os_images_interface | default(omit, true) }}"
Done

2021-05-21 08:07 UTC, markgoddard commented on tasks/main.yml
> +        region: "{{ os_images_region | default(omit) }}"
Docs say it's region_name: https://docs.ansible.com/ansible/2.9/modules/os_image_module.html

2021-05-21 08:08 UTC, markgoddard commented on defaults/main.yml
> +os_images_region:
os_images_region_name if we change the module args

2023-11-23 11:30 UTC, oneswig approved these changes
Fixes applied and tested with and without the parameter set

2023-11-23 11:40 UTC, markgoddard approved these changes

2023-11-23 11:40 UTC, merged